######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
logo_on_white: "images/k8up-logo.svg"
logo_on_black: "images/k8up-logo-white-text.svg"
custom_js: []
custom_css: ["css/announcement.css"]

######################## custom config ####################

# Announcement banner, shown above the header on the homepage only.
announcement:
  enabled: true
  text: "Join us at KubeCon + CloudNativeCon North America on Nov 9-12 🎉"
  link_text: "Register Today!"
  link: "https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/register/?utm_source=k8up&utm_medium=ribbon-banner&utm_campaign=KubeCon-CloudNativeCon-NA-2026&utm_content=hero"

### default social share image (can also be set per lang) ###
images: ["/images/social-share.png"]

github:
  repo_url: "https://github.com/k8up-io/website"
  show_edit_link: true

social_links:
  devstats: "https://k8up.devstats.cncf.io/"
  discord: ""
  facebook: ""
  flickr: ""
  github: "https://github.com/k8up-io/k8up"
  instagram: ""
  landscape: ""
  linkedin: ""
  mastodon: "https://mastodon.vshn.social/@k8up"
  pinterest: ""
  rss: ""
  slack: "https://app.slack.com/client/T08PSQ7BQ/C06GP0D5FEF"
  stackoverflow: ""
  threads: ""
  twitter: ""
  x: ""
  youtube: ""

# Makes the header sticky on tall screens
sticky_header: true
# Enable search in header UI
show_search: false
